//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateDocument
    {
        public int CandidateDocumentId { get; set; }
        public string DocumentName { get; set; }
        public int DocumentType { get; set; }
        public int DocumentSize { get; set; }
        public int CandidateId { get; set; }
        public string DocumentPath { get; set; }
    
        public virtual Candidate Candidate { get; set; }
    }
}
